"""create_product_table

Revision ID: 057bbfdb1c53
Revises: 660176346c34
Create Date: 2021-08-22 16:38:58.046440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057bbfdb1c53'
down_revision = '660176346c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('insert_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
