"""add one-many relationship between product, user and category table

Revision ID: 29cdf20d6a8d
Revises: f91237c28b3a
Create Date: 2021-08-26 23:13:53.802653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cdf20d6a8d'
down_revision = 'f91237c28b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_id', 'product', 'user', ['seller_id'], ['id'])
    op.create_foreign_key('fk_category_id', 'product', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_category_id', 'product', type_='foreignkey')
    op.drop_constraint('fk_user_id', 'product', type_='foreignkey')
    op.drop_column('product', 'category_id')
    op.drop_column('product', 'seller_id')
    # ### end Alembic commands ###
