"""create order_status table

Revision ID: 3439eb77940f
Revises: 92a446819fea
Create Date: 2021-09-26 11:09:35.551177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3439eb77940f'
down_revision = '92a446819fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('insert_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.add_column('order', sa.Column('order_status_id', sa.Integer(), nullable=True))
    op.create_foreign_key('order_status_fk', 'order', 'order_status', ['order_status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_status_fk', 'order', type_='foreignkey')
    op.drop_column('order', 'order_status_id')
    op.drop_table('order_status')
    # ### end Alembic commands ###
