"""create rating table

Revision ID: 45620d45da68
Revises: 29cdf20d6a8d
Create Date: 2021-08-27 23:06:58.793326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45620d45da68'
down_revision = '29cdf20d6a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('insert_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('ratee_id', sa.Integer(), nullable=False),
    sa.Column('order_item_order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_order_id', 'order_item_product_id'], ['order_item.order_id', 'order_item.product_id'], ),
    sa.ForeignKeyConstraint(['ratee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    # ### end Alembic commands ###
