"""create_category_table

Revision ID: 660176346c34
Revises: 238e19ee4211
Create Date: 2021-08-22 16:01:08.955938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660176346c34'
down_revision = '238e19ee4211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('insert_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
