"""change info column to newebpay_trade_sn

Revision ID: aabb2b40b139
Revises: c0584ec8b5cc
Create Date: 2021-10-01 12:39:30.569960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aabb2b40b139'
down_revision = 'c0584ec8b5cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('newebpay_trade_sn', sa.String(length=100), nullable=False))
    op.drop_column('payment', 'info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('info', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('payment', 'newebpay_trade_sn')
    # ### end Alembic commands ###
