"""add name and image column to order item table

Revision ID: c0584ec8b5cc
Revises: 3439eb77940f
Create Date: 2021-09-26 12:19:06.189824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0584ec8b5cc'
down_revision = '3439eb77940f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('name', sa.String(length=60), nullable=False))
    op.add_column('order_item', sa.Column('image_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'image_url')
    op.drop_column('order_item', 'name')
    # ### end Alembic commands ###
